# ==============================================================================
# GHOST KERNEL 100% PURE KERNEL CONFIGURATION FILE
# Location: /efs/ghost.conf (Primary) or /data/adb/ghost.conf (Secondary)
# ==============================================================================

[DEVICE]
model = SM-G991B
product = o1sxeea
device = o1s
manufacturer = samsung
brand = samsung
soc_machine = Exynos
soc_family = samsung

[FINGERPRINT]
build_fingerprint = samsung/o1sxeea/o1s:12/SP1A.210812.016/SM-G991BXXS3BULC:user/release-keys
build_desc = o1sxeea-user 12 SP1A.210812.016 SM-G991BXXS3BULC release-keys
build_id = SP1A.210812.016
security_patch = 2022-01-01

[HARDWARE_IDS]
serialno = R5CR792K18M
imei = 354892110293845
imei2 = 354892110293852
wifi_mac = A4:75:B9:44:55:66
bt_mac = A4:75:B9:44:55:67
ufs_serial = 0x9c4a8b12
ufs_model = KLUEG8UHDB-C2D1

[ENVIRONMENT_METRICS]
uptime_days = 17
boot_count = 38
battery_cycle = 142
battery_health = 96
sensor_bias = 12,-8,21
tcp_isn_offset = 0x1a2b3c4d

[VERIFIED_BOOT]
boot_hash = 7207368a4caca12d62f0382e67932c38f78c6d0b3f9bd7f5967825461b4172c1
boot_key = 22defff599279ee456bbae21e65c2623cf87660f8eb8cb50d91d5879d703a781
