package io.github.ghost.widevine;

import android.media.MediaDrm;
import android.util.Base64;
import android.util.Log;

import java.io.File;
import java.io.FileInputStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Arrays;

/**
 * GhostWidevineHook:
 * Intercepts android.media.MediaDrm.getPropertyByteArray and getPropertyString
 * to return the deterministic KDF 32-byte Widevine Device Unique ID generated by Ghost Kernel.
 */
public class GhostWidevineHook {
    private static final String TAG = "GhostWidevine";
    private static final String PROC_RAW = "/proc/ghost_widevine_raw";
    private static final String PROC_HEX = "/proc/ghost_widevine";
    private static byte[] cachedDeviceId = null;

    public static synchronized byte[] getGhostDeviceId() {
        if (cachedDeviceId != null && cachedDeviceId.length == 32) {
            return cachedDeviceId;
        }

        try {
            File rawFile = new File(PROC_RAW);
            if (rawFile.exists() && rawFile.canRead()) {
                byte[] raw = Files.readAllBytes(rawFile.toPath());
                if (raw.length == 32) {
                    cachedDeviceId = raw;
                    Log.i(TAG, "Loaded 32-byte ghost device unique id from " + PROC_RAW);
                    return cachedDeviceId;
                }
            }

            File hexFile = new File(PROC_HEX);
            if (hexFile.exists() && hexFile.canRead()) {
                String content = new String(Files.readAllBytes(hexFile.toPath()));
                for (String line : content.split("\n")) {
                    if (line.startsWith("widevine_device_id:")) {
                        String hex = line.substring("widevine_device_id:".length()).trim();
                        if (hex.length() == 64) {
                            byte[] parsed = new byte[32];
                            for (int i = 0; i < 32; i++) {
                                parsed[i] = (byte) Integer.parseInt(hex.substring(i * 2, i * 2 + 2), 16);
                            }
                            cachedDeviceId = parsed;
                            Log.i(TAG, "Loaded ghost device unique id from hex " + PROC_HEX);
                            return cachedDeviceId;
                        }
                    }
                }
            }
        } catch (Throwable t) {
            Log.e(TAG, "Failed to read ghost widevine ID: " + t.getMessage());
        }

        return null;
    }

    /**
     * Call this inside XC_MethodHook before/after getPropertyByteArray
     */
    public static byte[] hookGetPropertyByteArray(String propertyName, byte[] originalResult) {
        if ("deviceUniqueId".equals(propertyName) || MediaDrm.PROPERTY_DEVICE_UNIQUE_ID.equals(propertyName)) {
            byte[] fake = getGhostDeviceId();
            if (fake != null) {
                Log.d(TAG, "Spoofed MediaDrm.getPropertyByteArray(deviceUniqueId)");
                return fake;
            }
        }
        return originalResult;
    }

    /**
     * Call this inside XC_MethodHook before/after getPropertyString
     */
    public static String hookGetPropertyString(String propertyName, String originalResult) {
        if ("deviceUniqueId".equals(propertyName) || MediaDrm.PROPERTY_DEVICE_UNIQUE_ID.equals(propertyName)) {
            byte[] fake = getGhostDeviceId();
            if (fake != null) {
                String spoofedBase64 = Base64.encodeToString(fake, Base64.NO_WRAP);
                Log.d(TAG, "Spoofed MediaDrm.getPropertyString(deviceUniqueId) -> " + spoofedBase64);
                return spoofedBase64;
            }
        }
        return originalResult;
    }
}
